
import { extend } from '@react-three/fiber';
import * as THREE from 'three';

// Extend THREE with all the geometries and materials we use
extend(THREE);

// This ensures all THREE.js objects are available as JSX elements
declare global {
  namespace JSX {
    interface IntrinsicElements {
      // The types are automatically generated by @react-three/fiber
      // based on the extend() call above
    }
  }
}

export {};
