
import { extend, ReactThreeFiber } from '@react-three/fiber';
import * as THREE from 'three';

// Extend THREE with all the geometries and materials we use
extend(THREE);

// This ensures all THREE.js objects are available as JSX elements
declare global {
  namespace JSX {
    interface IntrinsicElements extends ReactThreeFiber.IntrinsicElements {
      // The types are automatically generated by @react-three/fiber
      // based on the extend() call above
    }
  }
  
  // Add __r3f property to HTMLCanvasElement for controls
  interface HTMLCanvasElement {
    __r3f?: {
      controls?: any;
    };
  }
}

export {};
